# Generated by Django 4.1 on 2023-02-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=225)),
                ("phone_number", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={"db_table": "Contact",},
        ),
    ]
