# Generated by Django 4.1 on 2023-02-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_contact_id"),
    ]

    operations = [
        migrations.AlterModelTable(name="contact", table="Contact Information",),
    ]
